# Generated by Django 2.1.7 on 2019-03-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicings',
            name='service_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicings',
            name='service_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicings',
            name='service_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
